version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: seplag_mt
      POSTGRES_PASSWORD: Seplag@Mt2025
      POSTGRES_DB: seplag_mt
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Laravel
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - postgres

  # Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - laravel

  # MinIO
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  minio-data:
